name: Z64 Workflow - Missing Song Detector

on:
  push:
    branches: [ "main" ] # Add here branches of your repo on which you want this script to trigger

jobs:
  build:
    #if: github.repository == 'CristobalPenaloza/Z64PackerTestRepo'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.x"]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Run checks
        run: python "z64_missing_song_detector.py" --ci
        
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          git add -A
          git commit -m "Run Z64 Workflow - Missing Song Detector"
          git push
